# Generated by Django 5.1.2 on 2024-11-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='neme',
            new_name='name',
        ),
    ]
