# Generated by Django 5.1.2 on 2024-11-28 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_product_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='a',
        ),
    ]
