# Generated by Django 5.1.2 on 2024-11-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_product_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='a',
            new_name='detail',
        ),
    ]
